### ISSUE TITLE
缓存的策略选择

### ISSUE THREAD

**Issue by lijianyu** [fengzhizi715/RxCache#1]
作者你好，非常感谢你开源的这个缓存库。不过我有个疑问，看代码好像，只能选择memory缓存或者disk缓存。比如我缓存一个对象，是否可以从memory中先获取，如果获取不到，再从disk中获取。这个方式可以进行配置，因为并不是所有情况都有这种情况。
还是已经支持了，我没看到😂

**Comment by fengzhizi715** [comment]
hi @lijianyu ，RxCache 可以支持你说的情况：
RxCache.config(new RxCache.Builder().memory(memoryImpl).persistence(diskImpl));
就可以了

**Comment by fengzhizi715** [comment]
如果memoryImpl、diskImpl都没有配置的话，会默认采用FIFOMemoryImpl。

**Comment by lijianyu** [comment]
> hi @lijianyu ，RxCache 可以支持你说的情况：
> RxCache.config(new RxCache.Builder().memory(memoryImpl).persistence(diskImpl));
> 就可以了

![image](https://user-images.githubusercontent.com/5039301/50499561-70265800-0a85-11e9-9a9e-e1c0bcd092e0.png)
我看获取的这一部分代码好像如果都配置了，走memory。然后直接return了。还是在其他地方，我没找到啊🤦‍♂️

**Comment by fengzhizi715** [comment]
@lijianyu  方便的话加一下我微信吧：fengzhizi715

**Comment by fengzhizi715** [comment]
已修复bug
