### ISSUE TITLE
proxy这块我觉得可以优化下。另外有没有考虑增加kotlin、协程的方式？

### ISSUE THREAD

**Issue by HuaZaiWuDi** [fengzhizi715/RxCache#4]
![image](https://user-images.githubusercontent.com/26106636/62017031-ac6e9200-b1e7-11e9-8094-c75b019b3653.png)

**Comment by HuaZaiWuDi** [comment]
不过感觉不需要另外支持，直接使用get方式就可以了。。。

**Comment by fengzhizi715** [comment]
hi，您可以发一个 pull request  ：）

**Comment by HuaZaiWuDi** [comment]
还有就是
![image](https://user-images.githubusercontent.com/26106636/62018296-b6df5a80-b1ec-11e9-9912-51cffc52b1ed.png)
这块可以简单点，直接使用@CacheRemove就可以吧，觉得用参数传递会比较麻烦，另外有个比较麻烦的问题，不知道大佬有没有好的方法可以解决。比如我希望在@CacheKey()拼接内容，如userId、分页码等等。请问这个有好的办法解决吗？
